server:
  port: 3035
spring:
  application:
    name: eureka_service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6544/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: 127.0.0.1

